# Generated by Django 6.0.3 on 2026-03-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=7)),
                ('children', models.PositiveIntegerField()),
                ('adults', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('allow_pets', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
